### ISSUE TITLE
Gone through your course at udemy.

### ISSUE THREAD

**Issue by engineernaman** [DL-Academy/pythonIgBot#3]
Never works completely. After scrolling it doesn't works. Help please.

**Comment by l-ami** [comment]
me too

**Comment by l-ami** [comment]
Traceback (most recent call last):
  File "C:\Users\\Documents\scripte py\IGBOT\main.py", line 75, in <module>
    main()
  File "C:\Users\\Documents\scripte py\IGBOT\main.py", line 26, in main
    run_bot(refs, driver, gp)
  File "C:\Users\\Documents\scripte py\IGBOT\main.py", line 38, in run_bot
    if gp.get_num_flw() < 3000:
  File "C:\Users\\Documents\scripte py\IGBOT\getpages.py", line 25, in get_num_flw
    return float(f)
ValueError: could not convert string to float: '1 259'
